version: '3'

services:
  micro-fe-container:
    build:
      context: ./micro-fe-container
      dockerfile: ./micro-fe-container.dockerfile
    restart: always
    ports:
      - "9000:80"
    deploy:
      mode: replicated
      replicas: 1

  micro-fe-application:
    build:
      context: ./micro-fe-application
      dockerfile: ./micro-fe-application.dockerfile
    restart: always
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1